### ISSUE TITLE
Finishing reference model: Coot crashes during real-space...

### ISSUE THREAD

**Issue by reskyner** [xchem/XChemExplorer#142]
... refinement on large regions.  (Patrick to send me an example that we can send to Paul Emsley) 

(Frank)

**Comment by tkrojer** [comment]
Bug is fixed. The reason for the crash was that XCE used gtk threading functionalities during refinement so that COOT would not freeze and a little spinner would indicate ongoing activity. However, this somewhow interferes with real space refinement. I've taken out threading, so COOT will now freeze, but the command line will output a status update every ten seconds.
