### ISSUE TITLE
Hydrogen atoms refinement: external restraints error 

### ISSUE THREAD

**Issue by reskyner** [xchem/XChemExplorer#21]
External restraints being generated, but not being able to find the associated atoms (thus refinement failing)

**Comment by nelse003** [comment]
The error occurs on the attempted refmac refinement of ligands with hydrogen atoms: 

Error: At least one of the atoms from the restraints could not be found:
 ==> exte dist first chain F resi    1 alte C atom  H16 second chain F resi    1 alte D atom  H16 value 0.0 sigma 0.02 type 1
   FF   1 H16 C

**Comment by nelse003** [comment]
Reply from Garib Murshudov:

The problem is related to hydrogen atoms. There are two ways of sorting it. First one is better than the second one:

1) Remove hydrogens in the input file. It can be done by running 0 cycles of refmac.
2) Add the following keyword in the beginning of the external reference file:

external missing ignore


The second option tells the program to ignore missing atoms. In general hydrogen atoms generated by different programs may have different names. refmac regenerates hydrogen atoms to make sure that their names are consistent within refmac run. Therefore sometimes it may cause problem.

**Comment by nelse003** [comment]
Next steps:

- Apply removal of hydrogen atoms from the input pdb file:

-  Try just in input protein & ligand pdb.

-  If not try altering at small molecule pdb stage/ check if cif need altering

- Whether implement hydrogen removal in all pipelines.

**Comment by reskyner** [comment]
Might it be easier to just remove H atoms with rdkit or something instead of running refmac?

**Comment by nelse003** [comment]
Yeah, I'm testing with: phenix.reduce model_h.pdb -trim > model_noH.pdb.

**Comment by nelse003** [comment]
Removing the hydrogen's from the  protein + ligand pdb file (ensemble model), and altering the list of external restraints in the file works to allow refinement to continue.

**Potential solutions**

1. Remove hydrogen atoms from compound pdb file at the point of generation

- It's not possible to remove hydrogen atoms directly in Acedrg. Might be possible in grade/phenix elbow 

2. Remove hydrogen atoms from  after generation, but before processing with Pandda

-  Cif file seems happy to provide restraints without hydrogens present

- Use phenix.reduce

3. Remove hydrogen atoms after processing with PanDDA, before refinement. Also requires adjustment of external restraints file (unlike solutions (1) and (2))

**Remaining Problems**

1. I don't know why refmac is happy with hydorgens in some cases and not in others?

- As Garib says it could be due to 

2. Do we need to retain the hydrogens in the compound files for any other reasons?

- We could keep a refinement compound file that has no hydrogens and use that for refinement, and processing by pandda.

**Next actions?**

I like solution 2, with added suggestion that we use a separate compound filename. 

- Who can inform whether we need to retain hydrogens for any other stage?

**Comment by nelse003** [comment]
Emailed Nick/ Frank to get their opinion . Will return to this when have opinion.

**Comment by nelse003** [comment]
I'm pretty sure they're absolutely pointless to keep. 

Worth checking if riding hydrogens are effectively added even for ligands - I imagine they are, because it's encoded in the CIF in some way.  Garib will know.

Anyway, if this fixes a blocker bug, then do it - life's to short to fuck around with hydrogens.

**Comment by nelse003** [comment]
I can remove hydrogens in the pdb file, but the connect records generated by grade are still there (and refer to incorrect places). I will test whether it improves the ability to pass through refinement.

**Comment by nelse003** [comment]
I feel this error is likely coming to light as we have switched to grade ?https://github.com/xchem/XChemExplorer/issues/61

**Comment by reskyner** [comment]
@nelse003 to devise a test (fast)

**Comment by nelse003** [comment]
Testing based on grade and acedrg, atripping the hydrogens before the restraints are generated, is sufficent to allow refinement. If this arises again, can text more throughouly. Stripping Hydrogens is now done by default, and included in recent commit.
